### ISSUE TITLE
Bot doesn't flame english man.

### ISSUE THREAD

**Issue by jonasschultheiss** [BAAAKA/DicordFlameBot#1]
As a user, i want that the bot flames engländers too, not just lol gamer kidz, so that the flame is splitt.

**Comment by quest1onmark** [comment]
spred luv <3

**Comment by BAAAKA** [comment]
![issue1](https://user-images.githubusercontent.com/28890343/70308524-c0687700-180b-11ea-8152-08e5b7517a79.PNG)
Bot is spreading love, but is unable to flame english man. The Issue is confirmed and will be fixed ASAP!
